name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          platform: linux
          arch: x64
        - os: ubuntu-22.04-arm64
          platform: linux
          arch: arm64
        - os: macos-12
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: windows-2022
          platform: win32
          arch: x64
        - os: windows-2022
          platform: win32
          arch: arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - uses: goto-bus-stop/setup-zig@v2
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.x'
    - run: npm install -g cmake-js
    - run: zig build -Doptimize=ReleaseFast && cmake-js clean && cmake-js compile
    - run: bun hello.js
    - run: node hello.js
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
        path: build/*